certamen3/certamen3/urls.py
from django.contrib import admin
from django.urls import path, include
from nuestrapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('rest/',include('rest.urls')),
    path('login/',views.login,name="login"),
]

certamen3/rest/urls.py
from rest_framework import routers
from .views import EventoViewSet
from django.urls import path, include

router = routers.DefaultRouter()
router.register('Evento',EventoViewSet)

urlpatterns = [
    path('',include(router.urls)),
]

certamen3/nuestrapp/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

TIPO_SEGMENTO = (
    ("C","Comunidad USM"),
    ("E","Estudiante"),
    ("P","Profesor"),
    ("J","Jefe de Carrera")
)
TIPO_TIPO = (
    ('V',"Vacaciones"),
    ('F',"Feriado"),
    ('SA',"Suspensión_de_actividades"),
    ('SAPM',"Suspensión_de_actividades_PM"),
    ('PL',"Periodo_Lectivo"),
    ('SE',"Suspensión_de_evaluaciones"),
    ('C',"Ceremonia"),
    ('EDDA',"EDDA"),
    ('E',"Evaluación"),
    ('A',"Ayudantías"),
    ('HA',"Hito_Académico"),
    ('SECA',"Secretaría_Académica"),
    ('OAI',"OAI")
    )    

class Evento(models.Model):
    fecha_inicio = models.DateTimeField()
    fecha_termino = models.DateTimeField()
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=300)
    
    tipo_tipo = models.CharField(max_length=10,choices=TIPO_TIPO)
    tipo_segmento = MultiSelectField(choices=TIPO_SEGMENTO,
                                max_length=10)
    def __str__(self) -> str:
        return self.titulo

class UsuarioSegmento(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_segmento = models.CharField(max_length=10,choices=TIPO_SEGMENTO,default="C")
    def __str__(self):
        return self.usuario.username
    

certamen3/rest/models.py
from django.db import models

# Create your models here.

certamen3/nuestrapp/views.py
from .models import Evento, User, UsuarioSegmento
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.hashers import check_password

# Create your views here.
#a
def index(request):

    respuestaSegmento = request.GET.get('Segmento')
    respuestaTipo = request.GET.get('Tipo')
    mostrar = False
    for u in UsuarioSegmento.objects.all():
        if u.usuario == request.user:
            segmento_usuario = u.tipo_segmento
            if (segmento_usuario in ["P","J"]):
                mostrar = True

    Usuario = request.user

    segmentos={"Comunidad_USM":'C',
                "Estudiante":'E',
                "Profesor":'P',
                "Jefe_de_Carrera":'J',
            }
    tipos = {"Vacaciones":'V',
            "Feriado":'F',
            "Suspensión_de_actividades":'SA',
            "Suspensión_de_actividades_PM":'SAPM',
            "Periodo_Lectivo":'PL',
            "Suspensión_de_evaluaciones":'SE',
            "Ceremonia":'C',
            "EDDA":'EDDA',
            "Evaluación":'E',
            "Ayudantías":'A',
            "Hito_Académico":'HA',
            "Secretaría_Académica":'SECA',
            "OAI":'OAI',
        }
    
    #filtro
    if (respuestaSegmento == 'Segmento' or respuestaSegmento == None) and (respuestaTipo == 'Tipo' or respuestaTipo == None): #Segmento none / Tipo none
        actividades = Evento.objects.all()

    elif (respuestaSegmento != 'Segmento') and (respuestaTipo != 'Tipo'): #Segmento [X] / Tipo [X]
        actividades = Evento.objects.filter(tipo_tipo__contains=tipos[respuestaTipo]).filter(tipo_segmento__contains=segmentos[respuestaSegmento])

    elif (respuestaSegmento != 'Segmento') and (respuestaTipo == 'Tipo' or respuestaTipo == None): #Segmento [X] / Tipo none
        actividades = Evento.objects.filter(tipo_segmento__contains=segmentos[respuestaSegmento])

    elif (respuestaSegmento == 'Segmento' or respuestaSegmento == None) and (respuestaTipo != 'Tipo'): #Segmento none / Tipo [X]
        actividades = Evento.objects.filter(tipo_tipo__contains=tipos[respuestaTipo])

    #fin_filtro
    actividades_siguientes = []
    c=0
    if (mostrar==True):
        for event in Evento.objects.filter(tipo_segmento__contains=segmento_usuario).order_by('-fecha_termino').reverse():
            if (c  < 3):
                actividades_siguientes.append(event)
            c+=1
        

    data={
        "actividades":actividades.order_by('-fecha_inicio').reverse(),
        "Segmentos":segmentos,
        "Tipos":tipos,
        "respuestaSegmento":respuestaSegmento,
        "respuestaTipo":respuestaTipo,
        "Usuario":Usuario,
        "mostrar":mostrar,
        "actividades_siguientes":actividades_siguientes,
    }
    return render(request, 'nuestrapp/base.html',data)

def login(request):
    users = []
    nombre = request.GET.get('usuario')
    contraseña = request.GET.get('contraseña')
    logeado = 1
    if (nombre != None) and (contraseña!=None):
        logeado = 3

    for u in User.objects.all():
        users.append((u.username,u.password))

    for usuario in users:
        if usuario[0] == nombre:
            if check_password(contraseña,usuario[1]):
                logeado = 2
    data={
        "Usuarios":users,
        "con":contraseña,
        "nombre":nombre,
        "si":logeado
    }
    return render(request,"nuestrapp/login.html",data)

certamen3/rest/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .serializers import EventoSerializer
from nuestrapp.models import Evento

class EventoViewSet(viewsets.ModelViewSet):
    queryset = Evento.objects.all()
    serializer_class = EventoSerializer
    http_method_names = ['get']

certamen3/nuestrapp/templates/nuestrapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendario Anual</title>
    <link rel="stylesheet" href="{%static 'nuestrapp/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'nuestrapp/css/estiloss.css'%}">
    <link href='https://fonts.googleapis.com/css?family=Roboto Condensed' rel='stylesheet'>
</head>
<body style="background-color:#000000">

    <div class="container-fluid">
        <div class="row borde"></div>
        <div id="inicio">
            <div class="row">
                <div class="col-4"><p style="font-size: 2vw;font-weight: bolder;text-align: center;">Bienvenido, {{Usuario}}</p></div>
                <div class="col-5"></div>
                <div class="col-3"><a href="http://127.0.0.1:8000/admin" class="btn" tabindex="-1" role="button" aria-disabled="true" style="min-width: 14vw;">Admin</a></div></div>
    
            </div>
        <div class="row borde"></div>
        <div class="row" id="logo">
            <div class="col-4"><img class="text-center" src="https://comunicaciones.usm.cl/wp-content/uploads/2023/09/logo_ref_horizontal_u.png" alt="logo usm" style="min-height: 30vh;"></div>
            <div class="col-8"><h1 style="font-size: 15vh;">Calendario USM</h1></div>
        </div>
        <div class="row borde"></div>
        <div class="row" id="calendario" style="background-color: #F7AE00;">
            {% include 'nuestrapp/calendario.html' %}
        </div>
        <div class="row borde"></div>
        {% if mostrar == True %}
            {% include 'nuestrapp/eventos.html' %}

        {% endif %}
            {% include 'nuestrapp/filtro.html' %}
        
            
            <div class="row borde"></div>
            {% include 'nuestrapp/tabla.html' %}
        <footer>
            <div class="row"><a href="https://github.com/Yarkowo/TLP-grupo-3">GitHub</a></div>
            
        </footer>
        <div class="row borde"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>

certamen3/nuestrapp/templates/nuestrapp/calendario.html
{%load static%}
<div class="row">
    <div class="col-1"></div>
    <div class="col-10"><img src="{% static 'nuestrapp/calendaricoso.png' %}" class="img-fluid" alt="(calendario)" style="max-height: 30vh;max-width: 60vw;"></div>
    <div class="col-1"></div>
</div>

certamen3/nuestrapp/templates/nuestrapp/eventos.html
<div class="row row-cols-1 row-cols-md-3 g-4" id="evento">
  {% for evento in actividades_siguientes %}
  <div class="col">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">{{evento.titulo}}</h5>
        <p class="card-text">{{evento.descripcion}}</p>
        <h5 class="card-title">{{evento.fecha_termino}}</h5>
      </div>
    </div>
  </div>
  {%endfor%}
</div>

certamen3/nuestrapp/templates/nuestrapp/filtro.html
<div class="row" id="filtro" style="background-color: #F7AE00;padding-bottom: 2vh;padding-top: 2vh;">
    <div class="col-1"></div>
    <div class="col-5">
        <form method="GET" action="">
            <select class="form-select" aria-label="Default select example" name="Segmento" onchange="this.form.submit()">
                <option value="Segmento" {% if respuestaSegmento == Segmento %} selected {% endif %}>Segmento</option>
                {%for Segmento in Segmentos%}
                <option value={{Segmento}} {% if respuestaSegmento == Segmento %} selected {% endif %} >{{Segmento}}</option>
                {%endfor%}
            </select>
    </div>

    <div class="col-5">
            <select class="form-select" aria-label="Default select example"  name="Tipo" onchange="this.form.submit()">
                <option value="Tipo"{% if respuestaTipo == Tipo %} selected {% endif %}>Tipo</option>
                {%for Tipo in Tipos%}
                <option value={{Tipo}} {% if respuestaTipo == Tipo %} selected {% endif %} >{{Tipo}}</option>
                {%endfor%}
            </select>
        </form>
    </div>
    <div class="col-1"></div>
</div>

certamen3/nuestrapp/templates/nuestrapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <div class="row">
        <div class="col-2"><p>Ingrese sus Datos</p></div>
        <div class="col"></div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            {% if si != 2 %}
            <form action="{% url 'login' %}" method="get">
                <label for="usuario" style="min-width: 200px;">Nombre de usuario:</label>
                <input type="text" id="usuario" name="usuario">
                <br><br>
                <label for="contraseña">Contraseña:</label>
                <input type="text" id="contraseña" name="contraseña">
                <br>
                <br>
                <input type="submit" value="Entrar">
            </form>

            <form action="{% url 'index' %}">
                <br>
                <input type="submit" value="Entrar como invitado">
            </form>
            {%endif%}

            {% if si == 3 %}
            <p>Acceso Denegado.</p>
            {%endif%}

            {% if si == 2 %}
            <p>Acceso Concedido.</p>
            <form action="{% url 'index' %}">
                <input type="submit" value="Continuar">
            </form>
            {% endif %}
        </div>
        <div class="col-2"></div>
    </div>
    
</body>
</html>

certamen3/nuestrapp/templates/nuestrapp/tabla.html
<div class="row">
</div>
<div class="row">
<table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Hito</th>
          <th scope="col">Fecha Inicio</th>
          <th scope="col">Fecha Termino</th>
          <th scope="col">Tipo</th>
          <th scope="col">Segmento</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for actividad in actividades %}
        <tr>
          <td>{{actividad.titulo}}</td>
          <td>{{actividad.fecha_inicio}}</td>
          <td>{{actividad.fecha_termino}}</td>
          <td>{{actividad.get_tipo_tipo_display}}</td>
          <td>{{actividad.get_tipo_segmento_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>